# Generated by Django 4.1.7 on 2023-04-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fromage',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fromage',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
