# Generated by Django 4.1.7 on 2023-04-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_commande_panier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='statut',
            new_name='validation',
        ),
    ]
