# Generated by Django 4.1.7 on 2023-04-24 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_rename_statut_commande_validation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='vendu',
            new_name='validation',
        ),
        migrations.AlterField(
            model_name='panier',
            name='date_commande',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 23, 59, 17, 473018, tzinfo=datetime.timezone.utc)),
        ),
    ]
