# Generated by Django 4.1.7 on 2023-04-25 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_rename_vendu_panier_validation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='validation',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 0, 55, 49, 259072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
