# Generated by Django 4.1.7 on 2023-04-25 03:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_alter_commande_date_commande_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.facture'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 3, 58, 19, 185268, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 3, 58, 19, 185268, tzinfo=datetime.timezone.utc)),
        ),
    ]
