# Generated by Django 4.1.7 on 2023-04-25 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_commande_facture_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 4, 16, 24, 842662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 4, 16, 24, 842662, tzinfo=datetime.timezone.utc)),
        ),
    ]
