# Generated by Django 5.0.7 on 2024-07-16 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
